/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidjniproject_MainActivity */

#ifndef _Included_com_example_androidjniproject_MainActivity
#define _Included_com_example_androidjniproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidjniproject_MainActivity
 * Method:    helloString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidjniproject_MainActivity_helloString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
